from typing import Protocol


class PaymentProvider(Protocol):
    async def create_payment(self, payment_id: str, amount_minor: int, currency: str) -> str: ...

    async def verify_payment(self, provider_payment_id: str) -> bool: ...

    async def process_webhook(self, payload: dict, secret: str) -> str: ...

    async def refund(self, provider_payment_id: str) -> None: ...
